// <auto-generated />
using System;
using AutodealerCrm;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutodealerCrm.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20251125105804_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("AutodealerCrm.CallDirection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DescriptionText")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CallDirections");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DescriptionText = "Inbound"
                        },
                        new
                        {
                            Id = 2,
                            DescriptionText = "Outbound"
                        });
                });

            modelBuilder.Entity("AutodealerCrm.CallRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CallDirectionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LeadId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecordingUrl")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ScriptScore")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Sentiment")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CallDirectionId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("LeadId");

                    b.HasIndex("ManagerId");

                    b.ToTable("call_records", (string)null);
                });

            modelBuilder.Entity("AutodealerCrm.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("TelegramId")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ViberId")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("WhatsappId")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("AutodealerCrm.Lead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LeadIntentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LeadStageId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("LeadIntentId");

                    b.HasIndex("LeadStageId");

                    b.HasIndex("ManagerId");

                    b.HasIndex("SourceChannelId");

                    b.ToTable("leads", (string)null);
                });

            modelBuilder.Entity("AutodealerCrm.LeadIntent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DescriptionText")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LeadIntents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DescriptionText = "Buy"
                        },
                        new
                        {
                            Id = 2,
                            DescriptionText = "Sell"
                        },
                        new
                        {
                            Id = 3,
                            DescriptionText = "Service Inquiry"
                        },
                        new
                        {
                            Id = 4,
                            DescriptionText = "Other"
                        });
                });

            modelBuilder.Entity("AutodealerCrm.LeadStage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DescriptionText")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LeadStages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DescriptionText = "New"
                        },
                        new
                        {
                            Id = 2,
                            DescriptionText = "Contacted"
                        },
                        new
                        {
                            Id = 3,
                            DescriptionText = "Qualified"
                        },
                        new
                        {
                            Id = 4,
                            DescriptionText = "In Negotiation"
                        },
                        new
                        {
                            Id = 5,
                            DescriptionText = "Prepayment"
                        },
                        new
                        {
                            Id = 6,
                            DescriptionText = "Sold"
                        },
                        new
                        {
                            Id = 7,
                            DescriptionText = "Lost"
                        });
                });

            modelBuilder.Entity("AutodealerCrm.LeadVehicle", b =>
                {
                    b.Property<int>("LeadId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VehicleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LeadId", "VehicleId");

                    b.HasIndex("VehicleId");

                    b.ToTable("lead_vehicles", (string)null);
                });

            modelBuilder.Entity("AutodealerCrm.Media", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("LeadId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("VehicleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("LeadId");

                    b.HasIndex("VehicleId");

                    b.ToTable("media", (string)null);
                });

            modelBuilder.Entity("AutodealerCrm.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LeadId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MediaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MessageChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MessageDirectionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MessageTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("LeadId");

                    b.HasIndex("ManagerId");

                    b.HasIndex("MediaId");

                    b.HasIndex("MessageChannelId");

                    b.HasIndex("MessageDirectionId");

                    b.HasIndex("MessageTypeId");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("AutodealerCrm.MessageChannel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DescriptionText")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MessageChannels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DescriptionText = "Viber"
                        },
                        new
                        {
                            Id = 2,
                            DescriptionText = "WhatsApp"
                        },
                        new
                        {
                            Id = 3,
                            DescriptionText = "Telegram"
                        },
                        new
                        {
                            Id = 4,
                            DescriptionText = "Email"
                        });
                });

            modelBuilder.Entity("AutodealerCrm.MessageDirection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DescriptionText")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MessageDirections");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DescriptionText = "Incoming"
                        },
                        new
                        {
                            Id = 2,
                            DescriptionText = "Outgoing"
                        });
                });

            modelBuilder.Entity("AutodealerCrm.MessageType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DescriptionText")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MessageTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DescriptionText = "Text"
                        },
                        new
                        {
                            Id = 2,
                            DescriptionText = "Photo"
                        },
                        new
                        {
                            Id = 3,
                            DescriptionText = "File"
                        },
                        new
                        {
                            Id = 4,
                            DescriptionText = "Voice Note"
                        });
                });

            modelBuilder.Entity("AutodealerCrm.SourceChannel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DescriptionText")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SourceChannels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DescriptionText = "Viber"
                        },
                        new
                        {
                            Id = 2,
                            DescriptionText = "WhatsApp"
                        },
                        new
                        {
                            Id = 3,
                            DescriptionText = "Telegram"
                        },
                        new
                        {
                            Id = 4,
                            DescriptionText = "Call"
                        },
                        new
                        {
                            Id = 5,
                            DescriptionText = "Email"
                        });
                });

            modelBuilder.Entity("AutodealerCrm.Task", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Completed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("LeadId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ManagerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LeadId");

                    b.HasIndex("ManagerId");

                    b.ToTable("tasks", (string)null);
                });

            modelBuilder.Entity("AutodealerCrm.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserRoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserRoleId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("AutodealerCrm.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DescriptionText")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DescriptionText = "Manager"
                        },
                        new
                        {
                            Id = 2,
                            DescriptionText = "Supervisor"
                        },
                        new
                        {
                            Id = 3,
                            DescriptionText = "Admin"
                        },
                        new
                        {
                            Id = 4,
                            DescriptionText = "Analyst"
                        });
                });

            modelBuilder.Entity("AutodealerCrm.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErpSyncId")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("VehicleStatusId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Vin")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.HasIndex("VehicleStatusId");

                    b.HasIndex("Vin")
                        .IsUnique();

                    b.ToTable("vehicles", (string)null);
                });

            modelBuilder.Entity("AutodealerCrm.VehicleStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DescriptionText")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("VehicleStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DescriptionText = "Available"
                        },
                        new
                        {
                            Id = 2,
                            DescriptionText = "Reserved"
                        },
                        new
                        {
                            Id = 3,
                            DescriptionText = "Sold"
                        },
                        new
                        {
                            Id = 4,
                            DescriptionText = "Archived"
                        });
                });

            modelBuilder.Entity("AutodealerCrm.CallRecord", b =>
                {
                    b.HasOne("AutodealerCrm.CallDirection", "CallDirection")
                        .WithMany()
                        .HasForeignKey("CallDirectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutodealerCrm.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AutodealerCrm.Lead", "Lead")
                        .WithMany()
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AutodealerCrm.User", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CallDirection");

                    b.Navigation("Customer");

                    b.Navigation("Lead");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("AutodealerCrm.Lead", b =>
                {
                    b.HasOne("AutodealerCrm.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AutodealerCrm.LeadIntent", "LeadIntent")
                        .WithMany()
                        .HasForeignKey("LeadIntentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutodealerCrm.LeadStage", "LeadStage")
                        .WithMany()
                        .HasForeignKey("LeadStageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutodealerCrm.User", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AutodealerCrm.SourceChannel", "SourceChannel")
                        .WithMany()
                        .HasForeignKey("SourceChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("LeadIntent");

                    b.Navigation("LeadStage");

                    b.Navigation("Manager");

                    b.Navigation("SourceChannel");
                });

            modelBuilder.Entity("AutodealerCrm.LeadVehicle", b =>
                {
                    b.HasOne("AutodealerCrm.Lead", "Lead")
                        .WithMany()
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AutodealerCrm.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lead");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("AutodealerCrm.Media", b =>
                {
                    b.HasOne("AutodealerCrm.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AutodealerCrm.Lead", "Lead")
                        .WithMany()
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AutodealerCrm.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Customer");

                    b.Navigation("Lead");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("AutodealerCrm.Message", b =>
                {
                    b.HasOne("AutodealerCrm.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AutodealerCrm.Lead", "Lead")
                        .WithMany()
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AutodealerCrm.User", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AutodealerCrm.Media", "Media")
                        .WithMany()
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AutodealerCrm.MessageChannel", "MessageChannel")
                        .WithMany()
                        .HasForeignKey("MessageChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutodealerCrm.MessageDirection", "MessageDirection")
                        .WithMany()
                        .HasForeignKey("MessageDirectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutodealerCrm.MessageType", "MessageType")
                        .WithMany()
                        .HasForeignKey("MessageTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Lead");

                    b.Navigation("Manager");

                    b.Navigation("Media");

                    b.Navigation("MessageChannel");

                    b.Navigation("MessageDirection");

                    b.Navigation("MessageType");
                });

            modelBuilder.Entity("AutodealerCrm.Task", b =>
                {
                    b.HasOne("AutodealerCrm.Lead", "Lead")
                        .WithMany()
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AutodealerCrm.User", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lead");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("AutodealerCrm.User", b =>
                {
                    b.HasOne("AutodealerCrm.UserRole", "UserRole")
                        .WithMany()
                        .HasForeignKey("UserRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("AutodealerCrm.Vehicle", b =>
                {
                    b.HasOne("AutodealerCrm.User", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AutodealerCrm.VehicleStatus", "VehicleStatus")
                        .WithMany()
                        .HasForeignKey("VehicleStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manager");

                    b.Navigation("VehicleStatus");
                });
#pragma warning restore 612, 618
        }
    }
}
