/*
This code was generated by an AI model for seeding a database using the Bogus library. 
When debugging read 'DataContext.cs' first to understand the structure of the database.
Your primary goal is to make the generated code compile and run successfully. 
If you fail you are allowed to regenerate the code and/or comment out functionality, but only as a last resort.
*/

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Bogus;
using Microsoft.EntityFrameworkCore;

namespace ShowcaseCrm;

public class DataSeeder : IDataSeeder
{
    private readonly DataContext _context;

    public DataSeeder(DataContext context)
    {
        _context = context;
    }

    public async System.Threading.Tasks.Task SeedAsync()
    {
        // Ensure LeadStatuses and DealStages are already seeded via HasData()
        var leadStatuses = await _context.LeadStatuses.ToArrayAsync();
        var dealStages = await _context.DealStages.ToArrayAsync();

        // Seed Users
        if (!await _context.Users.AnyAsync())
        {
            var userFaker = new Faker<User>()
                .RuleFor(u => u.Name, f => f.Person.FullName)
                .RuleFor(u => u.Email, f => f.Internet.Email())
                .RuleFor(u => u.CreatedAt, f => f.Date.Past(1))
                .RuleFor(u => u.UpdatedAt, (f, u) => f.Date.Between(u.CreatedAt, DateTime.UtcNow));

            var newUsers = userFaker.Generate(50);
            _context.Users.AddRange(newUsers);
            await _context.SaveChangesAsync();
        }

        var users = await _context.Users.ToArrayAsync();

        // Seed Companies
        if (!await _context.Companies.AnyAsync())
        {
            var companyFaker = new Faker<Company>()
                .RuleFor(c => c.Name, f => f.Company.CompanyName())
                .RuleFor(c => c.Address, f => f.Address.FullAddress())
                .RuleFor(c => c.Phone, f => f.Phone.PhoneNumber())
                .RuleFor(c => c.Website, f => f.Internet.Url())
                .RuleFor(c => c.CreatedAt, f => f.Date.Past(1))
                .RuleFor(c => c.UpdatedAt, (f, c) => f.Date.Between(c.CreatedAt, DateTime.UtcNow));

            var newCompanies = companyFaker.Generate(100);
            _context.Companies.AddRange(newCompanies);
            await _context.SaveChangesAsync();
        }

        var companies = await _context.Companies.ToArrayAsync();

        // Seed Contacts
        if (!await _context.Contacts.AnyAsync())
        {
            var contactFaker = new Faker<Contact>()
                .RuleFor(c => c.FirstName, f => f.Name.FirstName())
                .RuleFor(c => c.LastName, f => f.Name.LastName())
                .RuleFor(c => c.Email, f => f.Internet.Email())
                .RuleFor(c => c.Phone, f => f.Phone.PhoneNumber())
                .RuleFor(c => c.CreatedAt, f => f.Date.Past(1))
                .RuleFor(c => c.UpdatedAt, (f, c) => f.Date.Between(c.CreatedAt, DateTime.UtcNow))
                .RuleFor(c => c.CompanyId, f => f.PickRandom(companies).Id);

            var newContacts = contactFaker.Generate(300);
            _context.Contacts.AddRange(newContacts);
            await _context.SaveChangesAsync();
        }

        var contacts = await _context.Contacts.ToArrayAsync();

        // Seed Leads
        if (!await _context.Leads.AnyAsync())
        {
            var leadFaker = new Faker<Lead>()
                .RuleFor(l => l.Source, f => f.Company.CatchPhrase())
                .RuleFor(l => l.CreatedAt, f => f.Date.Past(1))
                .RuleFor(l => l.UpdatedAt, (f, l) => f.Date.Between(l.CreatedAt, DateTime.UtcNow))
                .RuleFor(l => l.CompanyId, f => f.PickRandom(companies).Id)
                .RuleFor(l => l.ContactId, f => f.PickRandom(contacts).Id)
                .RuleFor(l => l.StatusId, f => f.PickRandom(leadStatuses).Id);

            var newLeads = leadFaker.Generate(200);
            _context.Leads.AddRange(newLeads);
            await _context.SaveChangesAsync();
        }

        var leads = await _context.Leads.ToArrayAsync();

        // Seed Deals
        if (!await _context.Deals.AnyAsync())
        {
            var dealFaker = new Faker<Deal>()
                .RuleFor(d => d.Amount, f => f.Random.Decimal(1000, 100000))
                .RuleFor(d => d.CloseDate, f => f.Date.Between(DateTime.UtcNow.AddMonths(-6), DateTime.UtcNow))
                .RuleFor(d => d.CreatedAt, f => f.Date.Past(1))
                .RuleFor(d => d.UpdatedAt, (f, d) => f.Date.Between(d.CreatedAt, DateTime.UtcNow))
                .RuleFor(d => d.CompanyId, f => f.PickRandom(companies).Id)
                .RuleFor(d => d.ContactId, f => f.PickRandom(contacts).Id)
                .RuleFor(d => d.LeadId, f => f.PickRandom(leads).Id)
                .RuleFor(d => d.StageId, f => f.PickRandom(dealStages).Id);

            var newDeals = dealFaker.Generate(500);
            _context.Deals.AddRange(newDeals);
            await _context.SaveChangesAsync();
        }
    }
}