/*
This code was generated by an AI model for seeding a database using the Bogus library. 
When debugging read 'DataContext.cs' first to understand the structure of the database.
Your primary goal is to make the generated code compile and run successfully. 
If you fail you are allowed to regenerate the code and/or comment out functionality, but only as a last resort.
*/

using Bogus;
using Microsoft.EntityFrameworkCore;
using System;

namespace AutodealerCrm;

public class DataSeeder : IDataSeeder
{
    private readonly DataContext _context;

    public DataSeeder(DataContext context)
    {
        _context = context;
    }

    public async System.Threading.Tasks.Task SeedAsync()
    {
        if (!await _context.Users.AnyAsync())
        {
            var userRoles = await _context.UserRoles.ToArrayAsync();
            var faker = new Faker();
            var userFaker = new Faker<User>()
                .RuleFor(u => u.Name, f => f.Person.FullName)
                .RuleFor(u => u.Email, f => f.Internet.Email())
                .RuleFor(u => u.UserRoleId, f => f.PickRandom(userRoles).Id)
                .RuleFor(u => u.CreatedAt, f => f.Date.Past(1))
                .RuleFor(u => u.UpdatedAt, (f, u) => f.Date.Between(u.CreatedAt, DateTime.UtcNow));

            var usersToAdd = userFaker.Generate(50);
            _context.Users.AddRange(usersToAdd);
            await _context.SaveChangesAsync();
        }

        var users = await _context.Users.ToArrayAsync();

        if (!await _context.Customers.AnyAsync())
        {
            var usedEmails = new HashSet<string>();
            var customerFaker = new Faker<Customer>()
                .RuleFor(c => c.FirstName, f => f.Name.FirstName())
                .RuleFor(c => c.LastName, f => f.Name.LastName())
                .RuleFor(c => c.Email, f => f.Random.Bool() ? f.Internet.Email() : null)
                .RuleFor(c => c.ViberId, f => f.Random.Bool() ? f.Random.String2(10, "0123456789") : null)
                .RuleFor(c => c.WhatsappId, f => f.Random.Bool() ? f.Random.String2(10, "0123456789") : null)
                .RuleFor(c => c.TelegramId, f => f.Random.Bool() ? f.Random.String2(10, "0123456789") : null)
                .RuleFor(c => c.CreatedAt, f => f.Date.Past(1))
                .RuleFor(c => c.UpdatedAt, (f, c) => f.Date.Between(c.CreatedAt, DateTime.UtcNow));

            var customersToAdd = new List<Customer>();
            var faker = new Faker();
            for (int i = 0; i < 200; i++)
            {
                string? email = null;
                if (faker.Random.Bool())
                {
                    do
                    {
                        email = faker.Internet.Email();
                    } while (!usedEmails.Add(email));
                }

                var customer = customerFaker.Generate();
                customer.Email = email;
                customersToAdd.Add(customer);
            }

            _context.Customers.AddRange(customersToAdd);
            await _context.SaveChangesAsync();
        }

        var customers = await _context.Customers.ToArrayAsync();

        if (!await _context.Vehicles.AnyAsync())
        {
            var vehicleStatuses = await _context.VehicleStatuses.ToArrayAsync();
            var vehicleFaker = new Faker<Vehicle>()
                .RuleFor(v => v.Make, f => f.Vehicle.Manufacturer())
                .RuleFor(v => v.Model, f => f.Vehicle.Model())
                .RuleFor(v => v.Year, f => f.Date.Past(30).Year)
                .RuleFor(v => v.Vin, f => f.Vehicle.Vin())
                .RuleFor(v => v.Price, f => f.Random.Decimal(5000, 100000))
                .RuleFor(v => v.VehicleStatusId, f => f.PickRandom(vehicleStatuses).Id)
                .RuleFor(v => v.ManagerId, f => f.Random.Bool() ? f.PickRandom(users).Id : null)
                .RuleFor(v => v.ErpSyncId, f => f.Random.Bool() ? f.Random.String2(10, "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789") : null)
                .RuleFor(v => v.CreatedAt, f => f.Date.Past(1))
                .RuleFor(v => v.UpdatedAt, (f, v) => f.Date.Between(v.CreatedAt, DateTime.UtcNow));

            var vehiclesToAdd = vehicleFaker.Generate(100);
            _context.Vehicles.AddRange(vehiclesToAdd);
            await _context.SaveChangesAsync();
        }

        var vehicles = await _context.Vehicles.ToArrayAsync();

        if (!await _context.Leads.AnyAsync())
        {
            var leadStages = await _context.LeadStages.ToArrayAsync();
            var sourceChannels = await _context.SourceChannels.ToArrayAsync();
            var leadIntents = await _context.LeadIntents.ToArrayAsync();
            var leadFaker = new Faker<Lead>()
                .RuleFor(l => l.CustomerId, f => f.PickRandom(customers).Id)
                .RuleFor(l => l.ManagerId, f => f.Random.Bool() ? f.PickRandom(users).Id : null)
                .RuleFor(l => l.SourceChannelId, f => f.PickRandom(sourceChannels).Id)
                .RuleFor(l => l.LeadIntentId, f => f.PickRandom(leadIntents).Id)
                .RuleFor(l => l.LeadStageId, f => f.PickRandom(leadStages).Id)
                .RuleFor(l => l.Priority, f => f.Random.Bool() ? f.Random.Int(1, 5) : null)
                .RuleFor(l => l.Notes, f => f.Random.Bool() ? f.Lorem.Paragraph() : null)
                .RuleFor(l => l.CreatedAt, f => f.Date.Past(1))
                .RuleFor(l => l.UpdatedAt, (f, l) => f.Date.Between(l.CreatedAt, DateTime.UtcNow));

            var leadsToAdd = leadFaker.Generate(150);
            _context.Leads.AddRange(leadsToAdd);
            await _context.SaveChangesAsync();
        }

        var leads = await _context.Leads.ToArrayAsync();

        if (!await _context.LeadVehicles.AnyAsync())
        {
            var leadVehiclesToAdd = new List<LeadVehicle>();
            var faker = new Faker();
            foreach (var lead in leads)
            {
                var numVehicles = faker.Random.Int(1, 3);
                var selectedVehicles = new HashSet<int>();
                for (int i = 0; i < numVehicles && selectedVehicles.Count < vehicles.Length; i++)
                {
                    var vehicle = faker.PickRandom(vehicles);
                    if (selectedVehicles.Add(vehicle.Id))
                    {
                        leadVehiclesToAdd.Add(new LeadVehicle
                        {
                            LeadId = lead.Id,
                            VehicleId = vehicle.Id
                        });
                    }
                }
            }

            _context.LeadVehicles.AddRange(leadVehiclesToAdd);
            await _context.SaveChangesAsync();
        }

        if (!await _context.Media.AnyAsync())
        {
            var mediaFaker = new Faker<Media>()
                .RuleFor(m => m.FilePath, f => f.System.FilePath())
                .RuleFor(m => m.FileType, f => f.PickRandom("image/png", "image/jpeg", "application/pdf", "video/mp4"))
                .RuleFor(m => m.UploadedAt, f => f.Date.Past(1))
                .RuleFor(m => m.VehicleId, f => f.Random.Bool() ? f.PickRandom(vehicles).Id : null)
                .RuleFor(m => m.LeadId, f => f.Random.Bool() ? f.PickRandom(leads).Id : null)
                .RuleFor(m => m.CustomerId, f => f.Random.Bool() ? f.PickRandom(customers).Id : null)
                .RuleFor(m => m.CreatedAt, f => f.Date.Past(1))
                .RuleFor(m => m.UpdatedAt, (f, m) => f.Date.Between(m.CreatedAt, DateTime.UtcNow));

            var mediaToAdd = mediaFaker.Generate(100);
            _context.Media.AddRange(mediaToAdd);
            await _context.SaveChangesAsync();
        }

        var media = await _context.Media.ToArrayAsync();

        if (!await _context.Tasks.AnyAsync())
        {
            var taskFaker = new Faker<Task>()
                .RuleFor(t => t.LeadId, f => f.PickRandom(leads).Id)
                .RuleFor(t => t.ManagerId, f => f.PickRandom(users).Id)
                .RuleFor(t => t.Title, f => f.Lorem.Sentence(3, 5))
                .RuleFor(t => t.Description, f => f.Random.Bool() ? f.Lorem.Paragraph() : null)
                .RuleFor(t => t.DueDate, f => f.Date.Past(1))
                .RuleFor(t => t.Completed, (f, t) => f.Random.Bool() ? 1 : 0)
                .RuleFor(t => t.CreatedAt, f => f.Date.Past(1))
                .RuleFor(t => t.UpdatedAt, (f, t) => f.Date.Between(t.CreatedAt, DateTime.UtcNow));

            var tasksToAdd = taskFaker.Generate(200);
            _context.Tasks.AddRange(tasksToAdd);
            await _context.SaveChangesAsync();
        }

        if (!await _context.CallRecords.AnyAsync())
        {
            var callDirections = await _context.CallDirections.ToArrayAsync();
            var callRecordFaker = new Faker<CallRecord>()
                .RuleFor(cr => cr.CustomerId, f => f.PickRandom(customers).Id)
                .RuleFor(cr => cr.LeadId, f => f.Random.Bool(0.5f) ? f.PickRandom(leads).Id : null)
                .RuleFor(cr => cr.ManagerId, f => f.Random.Bool(0.7f) ? f.PickRandom(users).Id : null)
                .RuleFor(cr => cr.CallDirectionId, f => f.PickRandom(callDirections).Id)
                .RuleFor(cr => cr.StartTime, f => f.Date.Past(1))
                .RuleFor(cr => cr.EndTime, (f, cr) => cr.StartTime.AddMinutes(f.Random.Int(5, 120)))
                .RuleFor(cr => cr.Duration, (f, cr) => (int)(cr.EndTime - cr.StartTime).TotalMinutes)
                .RuleFor(cr => cr.RecordingUrl, f => f.Random.Bool(0.3f) ? f.Internet.Url() : null)
                .RuleFor(cr => cr.ScriptScore, f => f.Random.Bool(0.2f) ? f.Random.Decimal(0, 100) : null)
                .RuleFor(cr => cr.Sentiment, f => f.Random.Bool(0.2f) ? f.Random.Decimal(-1, 1) : null)
                .RuleFor(cr => cr.CreatedAt, (f, cr) => cr.StartTime)
                .RuleFor(cr => cr.UpdatedAt, (f, cr) => f.Date.Between(cr.CreatedAt, DateTime.UtcNow));

            var callRecordsToAdd = callRecordFaker.Generate(300);
            _context.CallRecords.AddRange(callRecordsToAdd);
            await _context.SaveChangesAsync();
        }

        if (!await _context.Messages.AnyAsync())
        {
            var messageChannels = await _context.MessageChannels.ToArrayAsync();
            var messageDirections = await _context.MessageDirections.ToArrayAsync();
            var messageTypes = await _context.MessageTypes.ToArrayAsync();
            var messageFaker = new Faker<Message>()
                .RuleFor(m => m.CustomerId, f => f.PickRandom(customers).Id)
                .RuleFor(m => m.LeadId, f => f.Random.Bool(0.6f) ? f.PickRandom(leads).Id : null)
                .RuleFor(m => m.ManagerId, f => f.Random.Bool(0.7f) ? f.PickRandom(users).Id : null)
                .RuleFor(m => m.MessageChannelId, f => f.PickRandom(messageChannels).Id)
                .RuleFor(m => m.MessageDirectionId, f => f.PickRandom(messageDirections).Id)
                .RuleFor(m => m.MessageTypeId, f => f.PickRandom(messageTypes).Id)
                .RuleFor(m => m.Content, f => f.Random.Bool(0.8f) ? f.Lorem.Sentence(5, 15) : null)
                .RuleFor(m => m.MediaId, f => f.Random.Bool(0.2f) && media.Length > 0 ? f.PickRandom(media).Id : null)
                .RuleFor(m => m.SentAt, f => f.Date.Past(1))
                .RuleFor(m => m.CreatedAt, (f, m) => m.SentAt)
                .RuleFor(m => m.UpdatedAt, (f, m) => f.Date.Between(m.CreatedAt, DateTime.UtcNow));

            var messagesToAdd = messageFaker.Generate(500);
            _context.Messages.AddRange(messagesToAdd);
            await _context.SaveChangesAsync();
        }
    }
}